# PythonGraphAppflow-SendEmailWithInlinePicture.py
# Initial code generated by Copilot.
#
# =============================
# Send an email with an inline image using Microsoft Graph API and Python.
# Prerequisites:
#   pip install msal requests
# Set up an Azure AD app with appropriate Graph API permissions (Mail.Send).
# Configure the constants below or set environment variables.
# Note: This example uses client credentials flow (app-only).
# Adjust as needed for delegated permissions.
# Reference: https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http
# Note: Inline images require the attachment to have "isInline": true and a matching "contentId".
# Adjust the image path and recipient as needed.
# Run the script: python PythonGraphAppflow-SendEmailWithInlinePicture.py

# Steps:
# 1. Acquire an app-only token with MSAL for scope https://graph.microsoft.com/.default.
# 2. Build a MIME-like HTML body that references an image by CID: cid:mylogo.
# 3. Attach the image as a file attachment with:
#  "isInline": true
#  "contentId": "mylogo"
#  "contentBytes": base64 of your image
#4. Call POST /users/{sender}/sendMail with the message payload.

# Note: A picture file is not included in this example.  Find one and save to a folder and then adjust the codepath to point to it.

# =============================   
# Import necessary libraries
# ============================
# 
import base64
import json
import os
import sys
import requests  # Run from the Visual Studio Code terminal window to install: python -m pip install requests
from msal import ConfidentialClientApplication # Run from the Visual Studio Code terminal window to install: python -m pip install msal

# ====== CONFIGURE THESE ======
TENANT_ID      = os.getenv("TENANT_ID",      "<your-tenant-id>")
CLIENT_ID      = os.getenv("CLIENT_ID",      "<your-client-id>")
CLIENT_SECRET  = os.getenv("CLIENT_SECRET",  "<your-client-secret>")
SENDER_USER    = os.getenv("SENDER_USER",    "sender@contoso.com")   # UPN or userId
RECIPIENTS     = [os.getenv("RECIPIENT",     "recipient@contoso.com")]
IMAGE_PATH     = os.getenv("IMAGE_PATH",     "logo.png")             # local file to embed
IMAGE_CONTENT_ID = "mylogo"  # must match cid: in the HTML
SUBJECT        = "Inline image via Microsoft Graph (Python)"
# =============================

AUTHORITY = f"https://login.microsoftonline.com/{TENANT_ID}"
SCOPE = ["https://graph.microsoft.com/.default"]
GRAPH_ROOT = "https://graph.microsoft.com/v1.0"

def get_app_token():
    app = ConfidentialClientApplication(
        client_id=CLIENT_ID,
        client_credential=CLIENT_SECRET,
        authority=AUTHORITY
    )
    result = app.acquire_token_silent(SCOPE, account=None)
    if not result:
        result = app.acquire_token_for_client(scopes=SCOPE)
    if "access_token" not in result:
        raise RuntimeError(f"Failed to acquire token: {result}")
    return result["access_token"]

def read_image_as_base64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")

def send_mail_with_inline_image():
    token = get_app_token()

    # HTML body referencing the image by contentId
    html_body = f"""
        <html>
          <body>
            <p>Hello,</p>
            <p>This message includes an inline image sent via Microsoft Graph.</p>
            <p><img src="cid:{IMAGE_CONTENT_ID}" alt="logo"gards,<br/>Python + Graph</p>
          </body>
        </html>
    """

    # Prepare recipients
    to_recipients = [{"emailAddress": {"address": r}} for r in RECIPIENTS]

    # Read and encode the image
    try:
        img_b64 = read_image_as_base64(IMAGE_PATH)
    except FileNotFoundError:
        print(f"Image not found: {IMAGE_PATH}", file=sys.stderr)
        sys.exit(1)

    # Build the message with an inline attachment
    message = {
        "subject": SUBJECT,
        "body": {
            "contentType": "HTML",
            "content": html_body
        },
        "toRecipients": to_recipients,
        "attachments": [
            {
                "@odata.type": "#microsoft.graph.fileAttachment",
                "name": os.path.basename(IMAGE_PATH),
                "contentId": IMAGE_CONTENT_ID,   # must match cid in HTML
                "isInline": True,
                "contentType": "image/png",      # adjust if not PNG
                "contentBytes": img_b64
            }
        ]
    }

    # Send the message
    url = f"{GRAPH_ROOT}/users/{SENDER_USER}/sendMail"
    payload = {"message": message, "saveToSentItems": True}
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }

    resp = requests.post(url, headers=headers, data=json.dumps(payload))
    if resp.status_code in (202, 200):
        print("Mail accepted for delivery.")
    else:
        print(f"Send failed: {resp.status_code}\n{resp.text}", file=sys.stderr)

if __name__ == "__main__":
    send_mail_with_inline_image()
 
